// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AnalyzeJobDescription(arg1:domain.JobAnalysisInput):Promise<domain.JobAnalysis>;

export function DeleteExperience(arg1:string):Promise<void>;

export function DeleteJob(arg1:string):Promise<void>;

export function DeleteEducation(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteResumeTemplate(arg1:string):Promise<void>;

export function CompileLatex(arg1:string):Promise<domain.CompileResult>;

export function CompileResumeVersion(arg1:string):Promise<domain.CompileResult>;

export function CreateResumeVersion(arg1:domain.CreateResumeVersionInput):Promise<domain.ApplicationResumeResult>;

export function ExportCompiledPDF():Promise<domain.FileResult>;

export function ExportLatexSource(arg1:string):Promise<domain.FileResult>;

export function ExportProfileBackup():Promise<domain.BackupResult>;

export function GetProfile():Promise<domain.Profile>;

export function GetSelectedResumeTemplateID():Promise<string>;

export function ImportProfileBackup():Promise<domain.BackupResult>;

export function ImportGitHubProjects():Promise<domain.GitHubImportResult>;

export function ImportResumeTemplate():Promise<domain.ResumeTemplate>;

export function ListExperiences():Promise<Array<domain.Experience>>;

export function ListApplications():Promise<Array<domain.Application>>;

export function ListJobs():Promise<Array<domain.Job>>;

export function ListEducations():Promise<Array<domain.Education>>;

export function ListProjects():Promise<Array<domain.Project>>;

export function ListResumeTemplates():Promise<Array<domain.ResumeTemplate>>;

export function RenderResumeTemplate(arg1:string,arg2:Array<string>):Promise<string>;

export function SaveExperience(arg1:domain.ExperienceInput):Promise<domain.Experience>;

export function SaveEducation(arg1:domain.EducationInput):Promise<domain.Education>;

export function SaveProject(arg1:domain.ProjectInput):Promise<domain.Project>;

export function SaveResumeTemplate(arg1:domain.ResumeTemplateInput):Promise<domain.ResumeTemplate>;

export function SaveResumeVersionEdit(arg1:domain.SaveResumeVersionEditInput):Promise<domain.ResumeVersion>;

export function SaveProfile(arg1:domain.ProfileInput):Promise<domain.Profile>;

export function SelectResumeTemplate(arg1:string):Promise<domain.ResumeTemplate>;
