// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeJobDescription(arg1) {
  return window['go']['main']['App']['AnalyzeJobDescription'](arg1);
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}
