// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptAITailoring(arg1) {
  return window['go']['main']['App']['AcceptAITailoring'](arg1);
}

export function AnalyzeJobDescription(arg1) {
  return window['go']['main']['App']['AnalyzeJobDescription'](arg1);
}

export function CancelAITailoring() {
  return window['go']['main']['App']['CancelAITailoring']();
}

export function CheckOllama(arg1) {
  return window['go']['main']['App']['CheckOllama'](arg1);
}

export function CompileLatex(arg1) {
  return window['go']['main']['App']['CompileLatex'](arg1);
}

export function CompileResumeVersion(arg1) {
  return window['go']['main']['App']['CompileResumeVersion'](arg1);
}

export function CreateResumeVersion(arg1) {
  return window['go']['main']['App']['CreateResumeVersion'](arg1);
}

export function DeleteEducation(arg1) {
  return window['go']['main']['App']['DeleteEducation'](arg1);
}

export function DeleteExperience(arg1) {
  return window['go']['main']['App']['DeleteExperience'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['main']['App']['DeleteJob'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteResumeTemplate(arg1) {
  return window['go']['main']['App']['DeleteResumeTemplate'](arg1);
}

export function ExportCompiledPDF() {
  return window['go']['main']['App']['ExportCompiledPDF']();
}

export function ExportLatexSource(arg1) {
  return window['go']['main']['App']['ExportLatexSource'](arg1);
}

export function ExportProfileBackup() {
  return window['go']['main']['App']['ExportProfileBackup']();
}

export function GenerateAITailoring(arg1) {
  return window['go']['main']['App']['GenerateAITailoring'](arg1);
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function GetSelectedResumeTemplateID() {
  return window['go']['main']['App']['GetSelectedResumeTemplateID']();
}

export function ImportGitHubProjects() {
  return window['go']['main']['App']['ImportGitHubProjects']();
}

export function ImportProfileBackup() {
  return window['go']['main']['App']['ImportProfileBackup']();
}

export function ImportResumeTemplate() {
  return window['go']['main']['App']['ImportResumeTemplate']();
}

export function ListAIRuns() {
  return window['go']['main']['App']['ListAIRuns']();
}

export function ListApplications() {
  return window['go']['main']['App']['ListApplications']();
}

export function ListEducations() {
  return window['go']['main']['App']['ListEducations']();
}

export function ListExperiences() {
  return window['go']['main']['App']['ListExperiences']();
}

export function ListJobs() {
  return window['go']['main']['App']['ListJobs']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListResumeTemplates() {
  return window['go']['main']['App']['ListResumeTemplates']();
}

export function RenderResumeTemplate(arg1, arg2) {
  return window['go']['main']['App']['RenderResumeTemplate'](arg1, arg2);
}

export function SaveEducation(arg1) {
  return window['go']['main']['App']['SaveEducation'](arg1);
}

export function SaveExperience(arg1) {
  return window['go']['main']['App']['SaveExperience'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SaveResumeTemplate(arg1) {
  return window['go']['main']['App']['SaveResumeTemplate'](arg1);
}

export function SaveResumeVersionEdit(arg1) {
  return window['go']['main']['App']['SaveResumeVersionEdit'](arg1);
}

export function SelectResumeTemplate(arg1) {
  return window['go']['main']['App']['SelectResumeTemplate'](arg1);
}
