// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AnalyzeJobDescription(arg1:domain.JobAnalysisInput):Promise<domain.JobAnalysis>;

export function GetProfile():Promise<domain.Profile>;

export function SaveProfile(arg1:domain.ProfileInput):Promise<domain.Profile>;
