// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AnalyzeJobDescription(arg1:domain.JobAnalysisInput):Promise<domain.JobAnalysis>;

export function DeleteExperience(arg1:string):Promise<void>;

export function DeleteEducation(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function GetProfile():Promise<domain.Profile>;

export function ListExperiences():Promise<Array<domain.Experience>>;

export function ListEducations():Promise<Array<domain.Education>>;

export function ListProjects():Promise<Array<domain.Project>>;

export function SaveExperience(arg1:domain.ExperienceInput):Promise<domain.Experience>;

export function SaveEducation(arg1:domain.EducationInput):Promise<domain.Education>;

export function SaveProject(arg1:domain.ProjectInput):Promise<domain.Project>;

export function SaveProfile(arg1:domain.ProfileInput):Promise<domain.Profile>;
